version: '3.7'

services:
  web:
    build: .
    command: gunicorn budget_app.wsgi -b 0.0.0.0:8001
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - .:/code
    ports:
      - 8001:8001
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
