# Generated by Django 3.0.5 on 2020-04-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('take_out_food', 'Take Out Food'), ('gas', 'Gas'), ('clothes', 'Clothes'), ('baby_stuff', 'Baby Stuff'), ('toiletries', 'Toiletries'), ('car_house', 'Car or House'), ('entertainment', 'Entertainment')], default='groceries', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(choices=[('red_card', 'Red Card'), ('amazon_card', 'Amazon Card'), ('greed_card', 'Green Card'), ('other', 'other')], default='green_card', max_length=20),
        ),
    ]
