# Generated by Django 3.0.5 on 2020-04-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20200418_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('take_out_food', 'Take Out Food'), ('gas', 'Gas'), ('clothes', 'Clothes'), ('baby_stuff', 'Baby Stuff'), ('toiletries', 'Toiletries'), ('car_house', 'Car or House'), ('entertainment', 'Entertainment'), ('drinks', 'Drinks'), ('dogs', 'Dogs'), ('medical', 'Medical'), ('other', 'Other')], default='groceries', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(choices=[('red_card', 'Red Card'), ('amazon_card', 'Amazon Card'), ('greed_card', 'Green Card'), ('other', 'Other')], default='green_card', max_length=20),
        ),
    ]
