# Generated by Django 3.0.7 on 2020-06-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_auto_20200505_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
